import { CalculatorMeta } from "@/types/calculator";

export const SITE_NAME = "CalcHub";
export const SITE_TITLE = "CalcHub — Free Online Calculator Tools | EMI, SIP, BMI & More";
export const SITE_DESCRIPTION =
  "Use 20+ free online calculators for EMI, SIP, BMI, GST, percentage, compound interest, GPA, unit conversion, and more. Fast, accurate, and mobile-friendly.";
export const SITE_URL = "https://calchub.com";

export const SOCIAL_LINKS = {
  twitter: "https://twitter.com/calchub",
  github: "https://github.com/calchub/calctools",
  linkedin: "https://linkedin.com/company/calchub",
};

const RAW_CALCULATORS: CalculatorMeta[] = [
  {
    slug: "emi-calculator",
    name: "EMI Calculator",
    shortDescription: "Calculate Equated Monthly Installment for home, car, and personal loans.",
    longDescription: "Quickly compute monthly loan payments, total interest, and complete amortization schedule.",
    category: "Finance",
    icon: "BadgePercent",
    popular: true,
    keywords: ["emi", "loan emi", "home loan emi", "car loan", "mortgage"],
    relatedSlugs: ["loan-calculator", "sip-calculator", "compound-interest-calculator", "fd-calculator"],
  },
  {
    slug: "sip-calculator",
    name: "SIP Calculator",
    shortDescription: "Estimate mutual fund SIP returns and wealth accumulated over time.",
    longDescription: "Calculate the expected future value of your systematic monthly mutual fund investments.",
    category: "Finance",
    icon: "TrendingUp",
    popular: true,
    keywords: ["sip", "mutual funds", "investment", "wealth creation", "returns"],
    relatedSlugs: ["compound-interest-calculator", "fd-calculator", "emi-calculator", "simple-interest-calculator"],
  },
  {
    slug: "bmi-calculator",
    name: "BMI Calculator",
    shortDescription: "Calculate your Body Mass Index (BMI) and check healthy weight ranges.",
    longDescription: "Accurately compute body mass index and find if you are underweight, normal, overweight, or obese.",
    category: "Health",
    icon: "Activity",
    popular: true,
    keywords: ["bmi", "body mass index", "weight", "health", "ideal weight"],
    relatedSlugs: ["calorie-calculator", "age-calculator", "unit-converter", "percentage-calculator"],
  },
  {
    slug: "percentage-calculator",
    name: "Percentage Calculator",
    shortDescription: "Find percentages, percentage differences, and proportional increases.",
    longDescription: "Three handy calculators in one: find X% of Y, what percent X is of Y, and percentage change.",
    category: "Math",
    icon: "Percent",
    popular: true,
    keywords: ["percentage", "percent change", "discount", "math", "fraction to percent"],
    relatedSlugs: ["discount-calculator", "gst-calculator", "profit-margin-calculator", "scientific-calculator"],
  },
  {
    slug: "age-calculator",
    name: "Age Calculator",
    shortDescription: "Calculate exact age in years, months, days, hours, and birthday countdown.",
    longDescription: "Determine exact age from birth date to any target date, along with zodiac and total days lived.",
    category: "Utility",
    icon: "Calendar",
    popular: true,
    keywords: ["age", "birthday", "birth date", "chronological age", "days lived"],
    relatedSlugs: ["days-between-dates-calculator", "time-calculator", "bmi-calculator", "calorie-calculator"],
  },
  {
    slug: "gst-calculator",
    name: "GST Calculator",
    shortDescription: "Calculate Goods and Services Tax (GST) inclusive and exclusive amounts.",
    longDescription: "Easily determine base price, CGST, SGST, IGST, and final gross amount with customizable tax slabs.",
    category: "Finance",
    icon: "Receipt",
    popular: true,
    keywords: ["gst", "tax", "cgst", "sgst", "vat", "sales tax"],
    relatedSlugs: ["discount-calculator", "profit-margin-calculator", "emi-calculator", "percentage-calculator"],
  },
  {
    slug: "loan-calculator",
    name: "Loan Calculator",
    shortDescription: "Estimate repayments and compare Home, Car, Personal, and Education loans.",
    longDescription: "In-depth loan calculator with loan type contextual advice, amortization schedule, and interest breakdowns.",
    category: "Finance",
    icon: "CreditCard",
    popular: false,
    keywords: ["loan", "interest", "home loan", "car loan", "personal loan"],
    relatedSlugs: ["emi-calculator", "compound-interest-calculator", "simple-interest-calculator", "sip-calculator"],
  },
  {
    slug: "fd-calculator",
    name: "FD Calculator",
    shortDescription: "Calculate Fixed Deposit maturity amount and compound interest earned.",
    longDescription: "Calculate maturity return for monthly, quarterly, semi-annual, and annual FD compounding.",
    category: "Finance",
    icon: "Landmark",
    popular: false,
    keywords: ["fd", "fixed deposit", "term deposit", "interest", "maturity"],
    relatedSlugs: ["compound-interest-calculator", "sip-calculator", "simple-interest-calculator", "emi-calculator"],
  },
  {
    slug: "compound-interest-calculator",
    name: "Compound Interest Calculator",
    shortDescription: "Compute compound growth with flexible frequencies and monthly additions.",
    longDescription: "Model exponential investment growth over time with customizable compounding periods and additions.",
    category: "Finance",
    icon: "Coins",
    popular: false,
    keywords: ["compound interest", "compounding", "investment growth", "future value"],
    relatedSlugs: ["simple-interest-calculator", "sip-calculator", "fd-calculator", "loan-calculator"],
  },
  {
    slug: "simple-interest-calculator",
    name: "Simple Interest Calculator",
    shortDescription: "Quickly compute basic interest on principal amounts over any duration.",
    longDescription: "Calculate simple interest and final total balance using the classic SI = (P × R × T) / 100 formula.",
    category: "Finance",
    icon: "DollarSign",
    popular: false,
    keywords: ["simple interest", "interest formula", "basic interest", "loans"],
    relatedSlugs: ["compound-interest-calculator", "fd-calculator", "emi-calculator", "percentage-calculator"],
  },
  {
    slug: "discount-calculator",
    name: "Discount Calculator",
    shortDescription: "Calculate sale price, total savings, and stacked discount percentages.",
    longDescription: "Determine final checkout prices after store discounts, coupon promotions, and multi-tier reductions.",
    category: "Math",
    icon: "Tag",
    popular: false,
    keywords: ["discount", "sale", "savings", "percentage off", "markdown"],
    relatedSlugs: ["percentage-calculator", "profit-margin-calculator", "gst-calculator", "unit-converter"],
  },
  {
    slug: "profit-margin-calculator",
    name: "Profit Margin Calculator",
    shortDescription: "Calculate gross profit margins, markups, and cost-revenue dynamics.",
    longDescription: "Easily switch between Profit Margin, Markup, and Gross Margin formulas to price products profitably.",
    category: "Finance",
    icon: "PieChart",
    popular: false,
    keywords: ["profit margin", "markup", "gross margin", "cost of goods", "cogs"],
    relatedSlugs: ["discount-calculator", "gst-calculator", "percentage-calculator", "currency-converter"],
  },
  {
    slug: "calorie-calculator",
    name: "Calorie Calculator",
    shortDescription: "Determine BMR and daily calorie targets for weight maintenance or loss.",
    longDescription: "Calculate Basal Metabolic Rate and daily caloric needs using the scientifically backed Mifflin-St Jeor equation.",
    category: "Health",
    icon: "Flame",
    popular: false,
    keywords: ["calories", "bmr", "tdee", "weight loss", "nutrition", "diet"],
    relatedSlugs: ["bmi-calculator", "age-calculator", "unit-converter", "time-calculator"],
  },
  {
    slug: "days-between-dates-calculator",
    name: "Days Between Dates Calculator",
    shortDescription: "Count exact calendar days, business days, and weekends between two dates.",
    longDescription: "Find elapsed time in days, weeks, months, business working days, and total hours between any two dates.",
    category: "Utility",
    icon: "CalendarRange",
    popular: false,
    keywords: ["days between dates", "date difference", "working days", "calendar duration"],
    relatedSlugs: ["age-calculator", "time-calculator", "unit-converter", "gpa-calculator"],
  },
  {
    slug: "gpa-calculator",
    name: "GPA Calculator",
    shortDescription: "Calculate your semester Grade Point Average on a 4.0 weighted scale.",
    longDescription: "Add your semester courses, grades, and credit hours to instantly compute your official GPA.",
    category: "Academic",
    icon: "GraduationCap",
    popular: false,
    keywords: ["gpa", "grade point average", "college grades", "semester gpa", "credits"],
    relatedSlugs: ["cgpa-calculator", "percentage-calculator", "age-calculator", "scientific-calculator"],
  },
  {
    slug: "cgpa-calculator",
    name: "CGPA Calculator",
    shortDescription: "Calculate Cumulative GPA and Indian percentage equivalent.",
    longDescription: "Combine multiple semesters with credit weighting to get your cumulative academic score and percentage conversion.",
    category: "Academic",
    icon: "Award",
    popular: false,
    keywords: ["cgpa", "cumulative gpa", "overall gpa", "cgpa to percentage", "university"],
    relatedSlugs: ["gpa-calculator", "percentage-calculator", "scientific-calculator", "unit-converter"],
  },
  {
    slug: "unit-converter",
    name: "Unit Converter",
    shortDescription: "Convert length, weight, temperature, volume, area, speed, and data units.",
    longDescription: "Comprehensive multi-unit converter supporting metric, imperial, digital storage, and scientific units.",
    category: "Utility",
    icon: "Scale",
    popular: false,
    keywords: ["unit converter", "length", "weight", "temperature", "metric conversion", "imperial"],
    relatedSlugs: ["currency-converter", "time-calculator", "scientific-calculator", "percentage-calculator"],
  },
  {
    slug: "currency-converter",
    name: "Currency Converter",
    shortDescription: "Convert between 30+ global currencies with live cached exchange rates.",
    longDescription: "Instant real-time currency conversion for USD, EUR, GBP, INR, JPY, CAD, AUD and more.",
    category: "Utility",
    icon: "RefreshCw",
    popular: false,
    keywords: ["currency converter", "forex", "exchange rate", "usd to inr", "eur to usd"],
    relatedSlugs: ["unit-converter", "profit-margin-calculator", "gst-calculator", "discount-calculator"],
  },
  {
    slug: "scientific-calculator",
    name: "Scientific Calculator",
    shortDescription: "Full on-screen scientific calculator with trigonometry, logs, and memory.",
    longDescription: "Powerful browser scientific calculator supporting angles (Deg/Rad), powers, roots, factorials, and history.",
    category: "Math",
    icon: "Calculator",
    popular: false,
    keywords: ["scientific calculator", "trigonometry", "sin cos tan", "math calculator", "logarithm"],
    relatedSlugs: ["percentage-calculator", "unit-converter", "time-calculator", "gpa-calculator"],
  },
  {
    slug: "time-calculator",
    name: "Time Calculator",
    shortDescription: "Add, subtract, and compute duration between time values in HH:MM:SS.",
    longDescription: "Calculate time differences, add or subtract hours, minutes, and seconds, with 12h/24h support.",
    category: "Utility",
    icon: "Clock",
    popular: false,
    keywords: ["time calculator", "hours and minutes", "time difference", "duration", "add time"],
    relatedSlugs: ["days-between-dates-calculator", "age-calculator", "unit-converter", "scientific-calculator"],
  },
];

export const CALCULATORS: CalculatorMeta[] = RAW_CALCULATORS.map((calc) => ({
  ...calc,
  id: calc.slug,
  description: calc.shortDescription,
}));
