import Link from "next/link";
import { PageSEO } from "@/components/seo";

export default function DisclaimerPage() {
  return (
    <>
      <PageSEO 
        title="Disclaimer | CalcHub"
        description="Read our financial, health, and accuracy disclaimers regarding the use of CalcHub tools."
        url="/disclaimer"
      />
      <div className="container mx-auto px-4 py-8 max-w-4xl">
        <nav className="text-sm mb-6 text-muted-foreground">
          <Link href="/" className="hover:underline">Home</Link> &gt; 
          <span className="ml-1">Disclaimer</span>
        </nav>

        <div className="prose prose-blue dark:prose-invert max-w-none">
          <h1 className="text-4xl font-bold mb-4">Disclaimer</h1>
          <p className="text-sm text-muted-foreground mb-8">Last Updated: March 2024</p>

          <p>
            The information and calculators provided by CalcHub (the "Site") are for general informational and educational purposes only. All information on the Site is provided in good faith, however, we make no representation or warranty of any kind, express or implied, regarding the accuracy, adequacy, validity, reliability, availability, or completeness of any information or calculation on the Site.
          </p>

          <h2>Financial Calculators Disclaimer</h2>
          <p>
            Our financial calculators (including but not limited to EMI, SIP, Loan, and Compound Interest calculators) are provided as estimation tools only. 
          </p>
          <ul>
            <li>They do not constitute professional financial, investment, or tax advice.</li>
            <li>Actual interest rates, loan terms, and investment returns may vary significantly based on market conditions, institutional policies, and individual credit scores.</li>
            <li>Always consult with a qualified financial advisor, accountant, or banking institution before making any significant financial decisions.</li>
          </ul>

          <h2>Health & Fitness Calculators Disclaimer</h2>
          <p>
            Calculators in our Health & Fitness category (such as BMI, Calorie, and Age calculators) are intended strictly for educational purposes.
          </p>
          <ul>
            <li>They are not intended to be a substitute for professional medical advice, diagnosis, or treatment.</li>
            <li>Always seek the advice of your physician or other qualified health provider with any questions you may have regarding a medical condition.</li>
            <li>Never disregard professional medical advice or delay in seeking it because of something you have read or calculated on this Site.</li>
          </ul>

          <h2>Accuracy of Information</h2>
          <p>
            While we strive to keep the calculators up-to-date and correct, errors may occasionally occur. If you spot an error, please <Link href="/contact">contact us</Link>. We are not liable for any losses or damages arising from reliance on the mathematical outcomes generated by this Site.
          </p>

          <h2>External Links Disclaimer</h2>
          <p>
            The Site may contain links to other websites or content belonging to or originating from third parties. Such external links are not investigated, monitored, or checked for accuracy, adequacy, validity, reliability, availability, or completeness by us. We do not warrant, endorse, guarantee, or assume responsibility for the accuracy or reliability of any information offered by third-party websites linked through the Site.
          </p>
        </div>
      </div>
    </>
  );
}
